import { describe, expect, it } from 'vitest';
import {
  DEFAULT_TITLE,
  findBrokenPages,
  fixSitemap,
  NOT_FOUND_MARKER,
} from './post-prerender';

/** Trimmed to the shape Analog emits, including the wrong namespace. */
const SITEMAP = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="https://www.sitemaps.org/schemas/sitemap/0.9">
  <!--This file was automatically generated by Analog.-->
  <url>
    <loc>https://ng-icons.github.io/ng-icons/</loc>
    <lastmod>2026-08-11</lastmod>
  </url>
  <url>
    <loc>https://ng-icons.github.io/ng-icons/browse</loc>
    <lastmod>2026-08-11</lastmod>
  </url>
  <url>
    <loc>https://ng-icons.github.io/ng-icons/404</loc>
    <lastmod>2026-08-11</lastmod>
  </url>
  <url>
    <loc>https://ng-icons.github.io/ng-icons/docs/introduction</loc>
    <lastmod>2026-08-11</lastmod>
  </url>
</urlset>
`;

describe('fixSitemap', () => {
  const NOT_FOUND_URL = 'https://ng-icons.github.io/ng-icons/404';
  const fixed = fixSitemap(SITEMAP, NOT_FOUND_URL);

  /**
   * The schema is published under http://. Declaring https:// makes it a
   * different namespace, which strict validators reject outright.
   */
  it('declares the namespace the schema is actually published under', () => {
    expect(fixed).toContain(
      'xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"',
    );
    expect(fixed).not.toContain('https://www.sitemaps.org');
  });

  it('drops the 404 page, which should never be offered for indexing', () => {
    expect(fixed).not.toContain('/ng-icons/404');
  });

  it('keeps every other page', () => {
    const locations = [...fixed.matchAll(/<loc>([^<]*)<\/loc>/g)].map(
      ([, url]) => url,
    );

    expect(locations).toEqual([
      'https://ng-icons.github.io/ng-icons/',
      'https://ng-icons.github.io/ng-icons/browse',
      'https://ng-icons.github.io/ng-icons/docs/introduction',
    ]);
  });

  it('leaves the document well-formed', () => {
    expect(fixed.trimStart()).toMatch(/^<\?xml/);
    expect(fixed.trimEnd()).toMatch(/<\/urlset>$/);
    expect(fixed.match(/<url>/g)).toHaveLength(3);
    expect(fixed.match(/<\/url>/g)).toHaveLength(3);
  });

  /** A real page can legitimately live at a path ending in 404. */
  it('keeps a real page whose own path ends in /404', () => {
    const xml = SITEMAP.replace(
      'https://ng-icons.github.io/ng-icons/404<',
      'https://ng-icons.github.io/ng-icons/docs/404<',
    );

    const result = fixSitemap(xml, NOT_FOUND_URL);

    expect(result).toContain('/ng-icons/docs/404');
    expect(result.match(/<url>/g)).toHaveLength(4);
  });

  /** A page whose path merely ends in 404 is a real page. */
  it('does not drop a page that only looks like the 404', () => {
    const xml = SITEMAP.replace(
      '/ng-icons/404<',
      '/ng-icons/docs/error-404-handling<',
    );

    expect(fixSitemap(xml, NOT_FOUND_URL)).toContain(
      '/docs/error-404-handling',
    );
  });
});

/**
 * Every one of these has happened. A blank docs page and a missing `/docs`
 * both left the build green, so the assertions live here rather than in a
 * reviewer's head.
 */
describe('findBrokenPages', () => {
  const page = (
    route: string,
    title: string,
    body = '<p>real content</p>',
  ) => ({
    route,
    html: `<html><head><title>${title}</title></head><body>${body}</body></html>`,
  });

  it('passes a site where every page rendered', () => {
    expect(
      findBrokenPages([
        page('/', `${DEFAULT_TITLE} \u00b7 Every icon set. One Angular API.`),
        page('/browse', `Browse icons \u00b7 ${DEFAULT_TITLE}`),
        page('/docs/installation', `Installation \u00b7 ${DEFAULT_TITLE}`),
      ]),
    ).toEqual([]);
  });

  it('catches a route that produced no file', () => {
    const problems = findBrokenPages([{ route: '/docs', html: null }]);

    expect(problems).toHaveLength(1);
    expect(problems[0].route).toBe('/docs');
    expect(problems[0].reason).toContain('nothing was written');
  });

  /** The docs shell rendered around content that never arrived. */
  it("catches a page still carrying index.html's title", () => {
    const problems = findBrokenPages([page('/docs', DEFAULT_TITLE)]);

    expect(problems).toHaveLength(1);
    expect(problems[0].reason).toContain('never applied its own');
  });

  it('catches a page that fell through to the catch-all', () => {
    const problems = findBrokenPages([
      page('/iconsets', `Icon sets \u00b7 ${DEFAULT_TITLE}`, NOT_FOUND_MARKER),
    ]);

    expect(problems).toHaveLength(1);
    expect(problems[0].reason).toContain('404');
  });

  it('allows the bare site title on the home page only', () => {
    expect(findBrokenPages([page('/', DEFAULT_TITLE)])).toEqual([]);
    expect(findBrokenPages([page('/browse', DEFAULT_TITLE)])).toHaveLength(1);
  });

  it('catches a page with no title at all', () => {
    expect(
      findBrokenPages([
        { route: '/browse', html: '<html><body>hi</body></html>' },
      ]),
    ).toHaveLength(1);
  });

  it('reports every broken page, not just the first', () => {
    expect(
      findBrokenPages([
        page('/', DEFAULT_TITLE),
        { route: '/browse', html: null },
        page('/iconsets', DEFAULT_TITLE),
      ]).map(problem => problem.route),
    ).toEqual(['/browse', '/iconsets']);
  });
});
